### ISSUE TITLE
iOS9 decryption done!

### ISSUE THREAD

**Issue by kam187** [foxsen/fairplay-server#3]
Hi,

I've managed to get the new airtunesd library working and returning the new challenges and key.  The challenges returned are the same as those I see in a network log so that's 100% is correct.  However decrypting the mirror traffic yields nonsense NALU's :/

You can follow my progress here:

https://github.com/espes/Slave-in-the-Magic-Mirror/issues/12

I'm not too sure where to go from here without a valid test vector to compare my key against.  I tried to send a request to your server to check if you were possible using the new library too but it refused the request.

Any help would be appreciated!

you can email me at my nick at gmail.com if you prefer.

**Comment by foxsen** [comment]
No, my library is current old one. And the server is not always running due to lack of server maintainence.

From what I know, the fp-setup things from ios9 is the same with ios8 but for receivers that support pairing(Feature has bit 31 set), the decrypted key will go through another treatment. You can try to find out that routine and add it.

Regards



zhangfx@lemote.com
 
From: kam187
Date: 2015-11-04 03:28
To: foxsen/fairplay-server
Subject: [fairplay-server] iOS9 decryption done! (#3)
Hi,
I've managed to get the new airtunesd library working and returning the new challenges and key. The challenges returned are the same as those I see in a network log so that's 100% is correct. However decrypting the mirror traffic yields nonsense NALU's :/
You can follow my progress here:
espes/Slave-in-the-Magic-Mirror#12
I'm not too sure where to go from here without a valid test vector to compare my key against. I tried to send a request to your server to check if you were possible using the new library too but it refused the request.
Any help would be appreciated!
you can email me at my nick at gmail.com if you prefer.
